# vim ft=yaml

# Notes below compliments of the scikit-image team:

# - Use http://yaml-online-parser.appspot.com/ to make sure the yaml
#   file is valid.  http://lint.travis-ci.org/ is recommended
#   elsewhere but does not give helpful error reports.

# - Make sure all of your "-" lines start on the same column

# - Use bash scripts for `before_install` and `script` or any part
#   that has conditional statements
#    - Make sure they are "executable" (chmod +x)
#    - Use the following header:

#    ```
#    #!/usr/bin/env bash
#    set -ex
#    ```

# - Use the `retry` bash function from `before_install.sh` before a
#   command to have it try 3 times before failing.

# - Use `pip install --retries N` for retrying package downloads.

# - Use the `section` function to start a folded section of the
#   script.  Section names must have underscores or dots instead of
#   spaces and must be accompanied by a corresponding `section_end`
#   call.

# - Feel free to cancel a build rather than waiting for it to go to
#   completion if you have made a change to that branch.

# - A VM with 64bit Ubuntu 12.04 is a huge help for debugging.

language: python
dist: bionic
sudo: required
cache:
  # See http://docs.travis-ci.com/user/caching/#pip-cache
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/sphinx
    - $HOME/.ccache
    - $HOME/.local
    - node_modules
addons:
  apt:
    packages:
      - ccache
      - wget
      - nodejs
      - unzip
  postgresql: "11"
  firefox: latest
env:
  global:
    - secure: "oyEPxoRtj+VYzWMDsf3PqWZHZMVw86e1OG5B5e0GS1lKudyi9eOKqiVpKO8Ra0II8Im5IFUKeuAePsJDy6Oxw2NyS6kvmxEWSysNF+qpEEFzqzdgAV7JfIN9PAslNGbq0CG17hEVDHh7Le5L/lNfHsP2/Qh5Dxy/eOh65KFhty0/etmp2cjYhQE8FYp5zRj4XKB83J/R7eGsvfKAJr2UX9DwyvczrGzTTaAU1Gqp5HhsSVLji3AA52OFvhmEKdh0YnGZMzO+DKZuXOPN7lZikkkiUcr1eGwdnKqulNj6viuo2x0t0QBAjoszbBvWgxz3luYihVRmGNO8NRbSgosVZl040so7rG56FCleuxZyc135AH9+U9j5BvBw2p8CSVbxtYIGJffUHoto0kJt5MwjFBo7jINmGyceam/AJM15lASd1DvEzTJuuTqts/As2Msp2pfNCQCuCadpBUY+zNBn7oKvz+cOobUDa8F0jNzexZPr9/8ejv/EKYPUgLux/MjGvWa/dX0tCePzAs6BhQUUdzwX6BGNHptnazIw41VpEJM8vmDP2P7nErOIH8M6pHCESuxb5pkRCjTqhBhSSUMFf88rJd6M9dHxBqzjkipDKRUpncZV+CXEKg13QBArPlkyzO8mNmqjE7cNsMaRNfK+3hBNEgpGCU0SrIH/RNlP/b0="

matrix:
  include:
    - python: 3.7
      env:
        - TEST_TARGET=test_headless

before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - which python; python --version
  - source .travis/travis_funcs.sh
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - .travis/travis_install.sh

script: .travis/travis_script.sh
